name: Publish release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ stdlib-release-pipeline ]

jobs:
  PublishPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21.0.3
      - name: "publish package"
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          packageUser: ${{ secrets.PACKAGEUSER }}
          packagePAT: ${{ secrets.PACKAGEPAT }}
          GITHUB_TOKEN: ${{ secrets.PACKAGEPAT }}
          CENTRAL_VERBOSE_ENABLED: true
        run: |
          ./gradlew -Pversion=2.14.0 build -x test -PpublishToCentral=true
